### PR TITLE
Add dutch (nl) translations

### PR DESCRIPTION
**Pull request by 112batman**

### CODE REVIEW

**Comment by 112batman** [comment]
I don't have a lot of time to work on this, feel free to merge the part that I did translate.

**Comment by 112batman** [comment]
Done translating, can now be merged.

**Comment by RetroPronghorn** [comment]
Please submit this as a new file to `nl.json` file instead of editing the `en_US.json` directly

**Comment by 112batman** [comment]
I did, for some reason git says I removed en_US (and added everything back). But you'll see I also added nl.json

**Comment by 112batman** [comment]
Resetting en_US to upstream master seems to have solved the problem

**Comment by RetroPronghorn** [comment]
Awesome, thanks for the addition! I'll add it into the options shortly.

**Pull request merged**
